"""Deterministic qualification test suite for Codex Audit Critical & High Remediation.

Covers:
C01: Credential watcher syntax, readiness handshake, and cleanup lifecycle.
C02: Untrusted candidate worktree validator isolation and environment sanitization.
H01: Git status whitespace preservation and rename handling.
H02: Canonical remote provenance and clean worktree guarantees.
H03: Git push verification and GitHub PR head/draft validation.
H04: Linear writeback terminal state verification.
H05: Corrupted execution ledger fail-closed handling.
H06: Dispatcher recovery external state and lease revalidation.
H07: Worker TaskState import and runtime stability.
H08: SQLite backup integrity verification.
H09: Backup _safe_copy_db raw copy rejection on active/corrupted DB.
H10: Quick snapshot restore path traversal and DB integrity verification.
H11: Offline evidence rollback rehearsal receipt requirement.
H12: Release gate workflow exact-head execution without echo bypass.
"""

from __future__ import annotations

import json
import os
import py_compile
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from ai_engineering.contracts import Status
from ai_engineering.linear_dispatcher.contracts import (
    BlockReasonCode,
    DispatcherConfig,
    LinearTask,
    TaskState,
)
from ai_engineering.linear_dispatcher.dispatcher import AutonomousDispatcher
from ai_engineering.linear_dispatcher.execution_ledger import (
    CorruptedLedgerError,
    ExecutionLedger,
    ExecutionState,
)
from ai_engineering.linear_dispatcher.task_executor import LinuxCodexTaskExecutor
from ai_engineering.linear_dispatcher.validator import LocalValidator
from ai_engineering.linear_dispatcher.worker import DispatcherWorker
from ai_engineering.linear_dispatcher.worktree_service import WorktreeService
from ai_engineering.linear_dispatcher.writeback import (
    ExecutionEvidence,
    WritebackService,
)
from hermes_cli.backup import _safe_copy_db, restore_quick_snapshot
from scripts.generate_offline_evidence import get_real_rollback_evidence


# ============================================================================
# C01: Credential Watcher Syntax & Lifecycle
# ============================================================================

def test_credential_watcher_syntax_is_valid_python(tmp_path: Path):
    """C01: Ensure watcher script generated by LinuxCodexTaskExecutor compiles cleanly."""
    executor = LinuxCodexTaskExecutor(credentials_path=tmp_path / "dummy_auth.json")
    script = executor._get_watcher_script("/tmp/test_dir")
    script_path = tmp_path / "watcher.py"
    script_path.write_text(script, encoding="utf-8")

    # py_compile should not raise SyntaxError
    compiled = py_compile.compile(str(script_path), doraise=True)
    assert compiled is not None


def test_credential_watcher_readiness_failure_fails_closed(tmp_path: Path):
    """C01: Ensure that failure of watcher to signal readiness fails closed without executing codex."""
    auth_file = tmp_path / "auth.json"
    auth_file.write_text("{}", encoding="utf-8")
    worktree = tmp_path / "worktree"
    worktree.mkdir()

    executor = LinuxCodexTaskExecutor(
        credentials_path=auth_file,
        is_windows=False,
    )
    # Stub health check to pass
    executor.health = MagicMock(return_value=True)
    executor._setup_ephemeral_credentials = MagicMock()

    # Mock Popen to simulate a process that immediately terminates or fails readiness
    mock_proc = MagicMock()
    mock_proc.poll.return_value = 1
    mock_proc.stderr.read.return_value = b"inotify error"

    task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test",
        description="",
        state="Todo",
        priority=1,
        assignee="agent",
        labels=(),
        created_at="",
        updated_at="",
        url="",
    )

    with patch("subprocess.Popen", return_value=mock_proc):
        result = executor.execute(task, worktree, "base_sha")
        assert result.status == "FAILED"
        assert result.error_reason == "CREDENTIAL_ISOLATION_FAILED"


# ============================================================================
# C02: Untrusted Validator Isolation
# ============================================================================

def test_validator_executes_only_from_trusted_root(tmp_path: Path):
    """C02: Ensure LocalValidator resolves validator scripts from trusted_root, not untrusted worktree."""
    trusted_root = tmp_path / "trusted_repo"
    trusted_scripts = trusted_root / "scripts"
    trusted_scripts.mkdir(parents=True)

    # Create real harmless scripts in trusted root
    (trusted_scripts / "check-windows-footguns.py").write_text("import sys; sys.exit(0)", encoding="utf-8")
    (trusted_scripts / "secret_scanner.py").write_text("import sys; sys.exit(0)", encoding="utf-8")

    # Create hostile trap in untrusted worktree
    untrusted_worktree = tmp_path / "untrusted_worktree"
    untrusted_scripts = untrusted_worktree / "scripts"
    untrusted_scripts.mkdir(parents=True)
    trap_file = tmp_path / "host_pwned.marker"
    hostile_code = f"import sys, pathlib; pathlib.Path(r'{trap_file}').write_text('PWNED'); sys.exit(0)"
    (untrusted_scripts / "check-windows-footguns.py").write_text(hostile_code, encoding="utf-8")
    (untrusted_scripts / "secret_scanner.py").write_text(hostile_code, encoding="utf-8")

    validator = LocalValidator()
    with patch.object(LocalValidator, "run_diff_check", return_value=(True, "")):
        overall_ok, results = validator.run_validation(untrusted_worktree, trusted_root=trusted_root)

    # Trap file must NOT exist
    assert not trap_file.exists()
    assert results.get("windows_footguns") == "PASS"
    assert results.get("secret_scanner") == "PASS"


def test_validator_environment_sanitizes_host_secrets(tmp_path: Path, monkeypatch):
    """C02: Ensure LocalValidator strips provider tokens and sensitive env vars from child execution."""
    monkeypatch.setenv("OPENAI_API_KEY", "sk-secret-12345")
    monkeypatch.setenv("GITHUB_TOKEN", "ghp_super_secret")
    monkeypatch.setenv("ANTHROPIC_API_KEY", "ant-secret-67890")

    trusted_root = tmp_path / "trusted_repo"
    trusted_scripts = trusted_root / "scripts"
    trusted_scripts.mkdir(parents=True)

    # Script checks that env vars are NOT present
    env_checker = """
import os, sys
for k in ("OPENAI_API_KEY", "GITHUB_TOKEN", "ANTHROPIC_API_KEY"):
    if k in os.environ:
        sys.exit(42)
sys.exit(0)
"""
    (trusted_scripts / "check-windows-footguns.py").write_text(env_checker, encoding="utf-8")
    (trusted_scripts / "secret_scanner.py").write_text(env_checker, encoding="utf-8")

    worktree = tmp_path / "worktree"
    worktree.mkdir(parents=True, exist_ok=True)
    validator = LocalValidator()
    with patch.object(LocalValidator, "run_diff_check", return_value=(True, "")):
        overall_ok, results = validator.run_validation(worktree, trusted_root=trusted_root)
    assert results.get("windows_footguns") == "PASS"
    assert results.get("secret_scanner") == "PASS"


# ============================================================================
# H01: Git Status Whitespace & Renames Handling
# ============================================================================

def test_git_changes_preserves_whitespace_and_renames(tmp_path: Path):
    """H01: Ensure _get_git_changes parses leading whitespace and file renames correctly."""
    dispatcher = AutonomousDispatcher(
        config=DispatcherConfig(),
        linear_client=MagicMock(),
        lease_manager=MagicMock(),
        worktree_service=MagicMock(),
        github_service=MagicMock(),
        worktree_base_dir=tmp_path / "worktrees",
        canonical_main_sha="canonical123",
    )

    # Mock git status output:
    # Line 1: ' M deploy/config.yml' (leading space for staged/unstaged)
    # Line 2: 'R  old_file.py -> new_file.py' (rename)
    # Line 3: '?? untracked.txt'
    fake_status = " M deploy/config.yml\nR  old_file.py -> new_file.py\n?? untracked.txt\n"

    with patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(returncode=0, stdout=fake_status)
        changes = dispatcher._get_git_changes(tmp_path)

    assert "deploy/config.yml" in changes
    assert "old_file.py" in changes
    assert "new_file.py" in changes
    assert "untracked.txt" in changes


# ============================================================================
# H02: Canonical Provenance & Clean Worktree Guarantees
# ============================================================================

def test_canonical_root_validation_rejects_non_canonical_urls(tmp_path: Path):
    """H02: Ensure validate_canonical_root strictly requires life2boat/hermes on GitHub."""
    worker = DispatcherWorker()
    with patch("subprocess.run") as mock_run:
        # Fork or attacker remote
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout="https://github.com/attacker/hermes.git\n",
        )
        ok, err = worker.validate_canonical_root(tmp_path)
        assert ok is False

        # Correct canonical remote
        mock_run.return_value = MagicMock(
            returncode=0,
            stdout="https://github.com/life2boat/hermes.git\n",
        )
        ok, err = worker.validate_canonical_root(tmp_path)
        assert ok is True


def test_worktree_service_reuses_only_clean_matching_worktree(tmp_path: Path):
    """H02: Ensure WorktreeService fails if an existing worktree is dirty or on wrong commit."""
    service = WorktreeService(canonical_root=tmp_path, base_sha="base123")
    target_dir = tmp_path / "worktrees"
    target_dir.mkdir(parents=True)

    task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test Task",
        description="",
        state="Todo",
        priority=1,
        assignee="agent",
        labels=("agent:auto", "agent:shadow"),
        created_at="2026-10-05T00:00:00Z",
        updated_at="2026-10-05T00:00:00Z",
        url="https://linear.app",
    )

    with patch("subprocess.run") as mock_run:
        # Mock status returns dirty worktree (returncode 0, stdout non-empty)
        mock_run.return_value = MagicMock(returncode=0, stdout=" M dirty_file.py\n")
        wt, branch, res = service.create_worktree(task, target_dir)
        assert wt is None
        assert res in (BlockReasonCode.STALE_WORKTREE_DIRTY, BlockReasonCode.DIRTY_CANONICAL_CHECKOUT)


# ============================================================================
# H03: Push Failure & PR Validation
# ============================================================================

def test_dispatcher_push_failure_fails_closed(tmp_path: Path):
    """H03: Ensure dispatcher fails closed if git push returns non-zero."""
    from ai_engineering.linear_dispatcher.task_executor import ExecutionResult

    mock_leases = MagicMock()
    mock_leases.is_held_by_foreign_worker.return_value = False
    mock_leases.claim.return_value = (True, MagicMock(claim_token="tok-1"), None)
    mock_leases.verify_lease.return_value = True

    mock_executor = MagicMock()
    mock_executor.execute.return_value = ExecutionResult(
        status="SUCCESS",
        changed_files=("changed.py",),
        execution_id="exec-1",
        executor_name="MockExecutor",
    )

    mock_validator = MagicMock()
    mock_validator.run_validation.return_value = (True, {})

    dispatcher = AutonomousDispatcher(
        config=DispatcherConfig(),
        linear_client=MagicMock(),
        lease_manager=mock_leases,
        worktree_service=MagicMock(),
        github_service=MagicMock(),
        worktree_base_dir=tmp_path / "worktrees",
        canonical_main_sha="canonical123",
        task_executor=mock_executor,
    )
    dispatcher._resolve_remote_main_sha = MagicMock(return_value="canonical123")
    dispatcher._validator = mock_validator

    task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test Task",
        description="",
        state="Todo",
        priority=1,
        assignee="agent",
        labels=("agent:auto", "agent:shadow"),
        created_at="2026-10-05T00:00:00Z",
        updated_at="2026-10-05T00:00:00Z",
        url="https://linear.app",
    )

    # Dispatch one task where push fails
    with patch("subprocess.run") as mock_run:
        def side_effect(cmd, **kwargs):
            if "push" in cmd:
                return MagicMock(returncode=1, stderr="fatal: remote rejected push")
            if "diff" in cmd and "--cached" in cmd:
                return MagicMock(returncode=0, stdout="changed.py\n")
            if "rev-parse" in cmd:
                return MagicMock(returncode=0, stdout="head123\n")
            return MagicMock(returncode=0, stdout="")
        mock_run.side_effect = side_effect

        # Mock worktree creation
        wt_path = tmp_path / "wt"
        wt_path.mkdir(parents=True, exist_ok=True)
        dispatcher._worktree_service.create_worktree.return_value = (wt_path, "feature-branch", None)
        dispatcher._get_git_changes = MagicMock(return_value=("changed.py",))

        res = dispatcher.dispatch_one_task([task])
        assert res is not None
        assert res.final_state == TaskState.FAILED
        assert res.block_reason == "GIT_PUSH_FAILED"


# ============================================================================
# H04: Linear Writeback Terminal State Verification
# ============================================================================

def test_writeback_verifies_terminal_state_confirmation():
    """H04: Ensure WritebackService confirms that issue transitioned to Done."""
    mock_client = MagicMock()
    mock_client.add_comment.return_value = True
    mock_client.update_issue.return_value = True

    stalled_task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test",
        description="",
        state="In Progress",
        priority=1,
        assignee="agent",
        labels=(),
        created_at="",
        updated_at="",
        url="",
    )
    evidence = ExecutionEvidence(
        task_id="HER-100",
        execution_status="SUCCESS",
        claim_owner="worker-1",
        branch="feature",
        pr_number=1,
        pr_url="https://github.com/pr/1",
        base_sha="base123",
        head_sha="head123",
        validation_status="PASS",
        ci_status="PASS",
        ci_head_sha="head123",
        sha_match="PASS",
    )
    # Re-reading issue returns issue still in "In Progress"
    mock_client.get_issue_comments.return_value = [evidence.to_markdown()]
    mock_client.get_issue.return_value = stalled_task

    writeback = WritebackService(linear_client=mock_client)
    ok, code = writeback.writeback_and_verify(
        task=stalled_task,
        evidence=evidence,
    )
    # Must fail because terminal state "Done" was not confirmed
    assert ok is False
    assert code == BlockReasonCode.REREAD_VERIFICATION_FAILED


# ============================================================================
# H05: Execution Ledger Corrupted State Handling
# ============================================================================

def test_execution_ledger_corrupted_data_raises_corrupted_ledger_error(tmp_path: Path):
    """H05: Ensure ExecutionLedger raises CorruptedLedgerError on corrupted json."""
    ledger_file = tmp_path / "ledger.json"
    ledger_file.write_text("{invalid json", encoding="utf-8")

    ledger = ExecutionLedger(persistence_path=ledger_file)
    with pytest.raises(CorruptedLedgerError):
        ledger.read_state()


# ============================================================================
# H06: Recovery External State & Lease Revalidation
# ============================================================================

def test_recovery_revalidates_ci_status_before_writeback(tmp_path: Path):
    """H06: Ensure recovery does not trust stale CI_PASS without re-verifying CI with GitHub."""
    mock_github = MagicMock()
    # GitHub reports CI is actually FAILING now
    mock_github.get_ci_status.return_value = (False, None, BlockReasonCode.CI_FAILED)

    mock_leases = MagicMock()
    mock_leases.verify_lease.return_value = True

    dispatcher = AutonomousDispatcher(
        config=DispatcherConfig(),
        linear_client=MagicMock(),
        lease_manager=mock_leases,
        worktree_service=MagicMock(),
        github_service=mock_github,
        worktree_base_dir=tmp_path / "worktrees",
        canonical_main_sha="canonical123",
    )

    recovery_state = ExecutionState(
        task_id="HER-100",
        state=TaskState.CI_PASS.value,
        claim_owner="hermes-autonomous-dispatcher-v1",
        claim_token="token-1",
        branch="agent/her-100",
        pr_number=1,
        pr_url="https://github.com/life2boat/hermes/pull/1",
        head_sha="head123",
        base_sha="base123",
    )

    # Recovery should revalidate with GitHub and reject stale CI_PASS
    recovered = dispatcher.recover_task(recovery_state)
    assert recovered.final_state == TaskState.BLOCKED
    assert recovered.block_reason == "CI_PASS_REVALIDATION_FAILED"


# ============================================================================
# H07: Worker TaskState Import
# ============================================================================

def test_worker_imports_task_state():
    """H07: Ensure worker module imports TaskState cleanly without NameError."""
    import ai_engineering.linear_dispatcher.worker as worker_module
    assert hasattr(worker_module, "TaskState")
    assert worker_module.TaskState.BLOCKED.value == "BLOCKED"


# ============================================================================
# H08 & H09: Backup Safe Copy DB & Verification
# ============================================================================

def test_safe_copy_db_rejects_corrupted_database(tmp_path: Path):
    """H08 & H09: Ensure _safe_copy_db rejects corrupt SQLite file without raw copy fallback."""
    src = tmp_path / "corrupt.db"
    src.write_text("This is not a SQLite database header", encoding="utf-8")
    dst = tmp_path / "backup.db"

    success = _safe_copy_db(src, dst)
    assert success is False
    assert not dst.exists()


# ============================================================================
# H10: Quick Snapshot Path Traversal & DB Integrity
# ============================================================================

def test_restore_quick_snapshot_blocks_path_traversal(tmp_path: Path):
    """H10: Ensure restore_quick_snapshot blocks path traversal in manifest."""
    home = tmp_path / "hermes_home"
    home.mkdir()
    snap_dir = home / "state-snapshots" / "snap-001"
    snap_dir.mkdir(parents=True)

    # Malicious manifest pointing outside home
    manifest = {
        "files": {
            "../../escaped.txt": 10,
        }
    }
    (snap_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")
    (snap_dir / "../../escaped.txt").parent.mkdir(parents=True, exist_ok=True)
    (snap_dir / "escaped.txt").write_text("evil", encoding="utf-8")

    # Destination outside home
    outside_file = tmp_path / "escaped.txt"
    if outside_file.exists():
        outside_file.unlink()

    restored = restore_quick_snapshot("snap-001", hermes_home=home)
    assert not outside_file.exists()
    assert restored is False


def test_restore_quick_snapshot_validates_db_integrity(tmp_path: Path):
    """H10: Ensure restore_quick_snapshot validates SQLite integrity before atomic replacement."""
    home = tmp_path / "hermes_home"
    home.mkdir()
    valid_db = home / "state.db"

    # Pre-create a valid DB at destination
    with sqlite3.connect(valid_db) as conn:
        conn.execute("CREATE TABLE t (id INT);")

    snap_dir = home / "state-snapshots" / "snap-bad-db"
    snap_dir.mkdir(parents=True)
    (snap_dir / "state.db").write_text("NOT A REAL SQLITE DATABASE", encoding="utf-8")
    manifest = {"files": {"state.db": 26}}
    (snap_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

    # Restore must reject bad DB and keep valid DB intact
    restored = restore_quick_snapshot("snap-bad-db", hermes_home=home)
    assert restored is False

    # Check original valid DB is still intact
    with sqlite3.connect(valid_db) as conn:
        res = conn.execute("PRAGMA integrity_check").fetchall()
        assert res == [("ok",)]


# ============================================================================
# H11: Offline Evidence Rollback Rehearsal Receipt Requirement
# ============================================================================

def test_offline_evidence_rollback_blocks_without_rehearsal_receipt(tmp_path: Path, monkeypatch):
    """H11: Ensure get_real_rollback_evidence returns BLOCKED if rehearsal receipt is absent."""
    monkeypatch.setenv("HERMES_ROLLBACK_REHEARSAL_PATH", str(tmp_path / "nonexistent.json"))

    # Even if docker inspect returns valid image info, missing receipt must block
    fake_inspect = json.dumps([{
        "Image": "healbite:latest@sha256:1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef",
        "Config": {"Labels": {"org.opencontainers.image.revision": "rev123"}},
    }])

    with patch("subprocess.check_output", return_value=fake_inspect.encode("utf-8")):
        ev = get_real_rollback_evidence("rev123", "2026-10-06T00:00:00Z")
        assert ev["status"] == "BLOCKED"


# ============================================================================
# H12: Release Gate Workflow Exact-Head & No Echo Bypass
# ============================================================================

def test_release_gate_workflow_executes_real_cli_without_echo_bypass():
    """H12: Ensure agent-release-gate.yml executes check_agent_release_gate.py ci-merge directly."""
    workflow_path = Path(__file__).resolve().parents[2] / ".github/workflows/agent-release-gate.yml"
    content = workflow_path.read_text(encoding="utf-8")

    # Must invoke the real script in ci-merge mode
    assert "uv run python scripts/check_agent_release_gate.py ci-merge" in content
    # Must NOT have echo bypass
    assert "echo '{\"status\": \"PASS\"}'" not in content
    assert 'echo "{\\"status\\": \\"PASS\\"}"' not in content
    # Must bind exact PR head SHA
    assert "github.event.pull_request.head.sha" in content


# ============================================================================
# C01 Additions: Death After READY, Build Failure, Unlinked Verification
# ============================================================================

def test_credential_watcher_death_after_ready_fails_closed(tmp_path: Path):
    """C01: If watcher process dies after READY before execution, executor must fail closed."""
    auth_file = tmp_path / "auth.json"
    auth_file.write_text("{}", encoding="utf-8")
    worktree = tmp_path / "worktree"
    worktree.mkdir()

    executor = LinuxCodexTaskExecutor(
        credentials_path=auth_file,
        is_windows=False,
    )
    executor.health = MagicMock(return_value=True)
    executor._setup_ephemeral_credentials = MagicMock()

    mock_proc = MagicMock()
    mock_proc.poll.return_value = 1
    mock_proc.returncode = 1

    def start_watcher(h):
        executor._watcher_proc = mock_proc

    executor._start_credential_unlinking_watcher = start_watcher

    task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test",
        description="",
        state="Todo",
        priority=1,
        assignee="agent",
        labels=(),
        created_at="",
        updated_at="",
        url="",
    )

    result = executor.execute(task, worktree, "base_sha")
    assert result.status == "FAILED"
    assert result.error_reason == "CREDENTIAL_ISOLATION_FAILED"


def test_command_build_failure_cleans_up_ephemeral_credentials(tmp_path: Path):
    """C01: Exception in build_bwrap_command must invoke _cleanup_ephemeral_credentials."""
    auth_file = tmp_path / "auth.json"
    auth_file.write_text("{}", encoding="utf-8")
    worktree = tmp_path / "worktree"
    worktree.mkdir()

    executor = LinuxCodexTaskExecutor(
        credentials_path=auth_file,
        is_windows=False,
    )
    executor.health = MagicMock(return_value=True)
    executor._setup_ephemeral_credentials = MagicMock()
    executor._start_credential_unlinking_watcher = MagicMock()
    cleanup_mock = MagicMock()
    executor._cleanup_ephemeral_credentials = cleanup_mock

    executor.build_bwrap_command = MagicMock(side_effect=RuntimeError("BUILD_FAIL"))

    task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test",
        description="",
        state="Todo",
        priority=1,
        assignee="agent",
        labels=(),
        created_at="",
        updated_at="",
        url="",
    )

    result = executor.execute(task, worktree, "base_sha")
    assert result.status == "FAILED"
    assert cleanup_mock.called


def test_unlinked_verification_failure_fails_closed(tmp_path: Path):
    """C01: If credentials are not unlinked during run, execute must fail closed."""
    auth_file = tmp_path / "auth.json"
    auth_file.write_text("{}", encoding="utf-8")
    worktree = tmp_path / "worktree"
    worktree.mkdir()

    executor = LinuxCodexTaskExecutor(
        credentials_path=auth_file,
        is_windows=False,
    )
    executor.health = MagicMock(return_value=True)
    executor._setup_ephemeral_credentials = MagicMock()
    executor._start_credential_unlinking_watcher = MagicMock()
    executor._cleanup_ephemeral_credentials = MagicMock()
    executor._runner = MagicMock(return_value=MagicMock(returncode=0))
    executor._verify_credential_unlinked = MagicMock(return_value=False)

    task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test",
        description="",
        state="Todo",
        priority=1,
        assignee="agent",
        labels=(),
        created_at="",
        updated_at="",
        url="",
    )

    result = executor.execute(task, worktree, "base_sha")
    assert result.status == "FAILED"
    assert result.error_reason == "CREDENTIAL_UNLINK_VERIFICATION_FAILED"


# ============================================================================
# C02 Additions: Candidate Host Execution Blocking
# ============================================================================

def test_validator_blocks_candidate_host_test_execution(tmp_path: Path):
    """C02: LocalValidator blocks run_tests=True on untrusted candidate worktrees."""
    untrusted = tmp_path / "untrusted"
    untrusted.mkdir()
    with patch.object(LocalValidator, "run_diff_check", return_value=(True, "")):
        ok, res = LocalValidator.run_validation(untrusted, run_tests=True, trusted_root=tmp_path)
    assert ok is False
    assert "pytest" in res
    assert "forbidden" in res["pytest"]


# ============================================================================
# H05 & H06 Additions: COMMITTED & BRANCH_PUSHED In Ledger, Fencing Before Cleanup
# ============================================================================

def test_dispatcher_records_committed_and_branch_pushed_in_ledger(tmp_path: Path):
    """H05: Dispatcher records durable COMMITTED and BRANCH_PUSHED states in ledger."""
    from ai_engineering.linear_dispatcher.task_executor import ExecutionResult

    ledger_path = tmp_path / "ledger.json"
    ledger = ExecutionLedger(ledger_path)

    mock_leases = MagicMock()
    mock_leases.is_held_by_foreign_worker.return_value = False
    mock_leases.claim.return_value = (True, MagicMock(claim_token="tok-1"), None)
    mock_leases.verify_lease.return_value = True

    mock_executor = MagicMock()
    mock_executor.execute.return_value = ExecutionResult(
        status="SUCCESS",
        changed_files=("feat.py",),
        execution_id="exec-1",
        executor_name="MockExecutor",
    )

    mock_validator = MagicMock()
    mock_validator.run_validation.return_value = (True, {})

    mock_github = MagicMock()
    from ai_engineering.linear_dispatcher.github_service import PRCreationResult, CIStatusResult
    mock_github.create_draft_pr.return_value = (
        True,
        PRCreationResult(
            pr_number=42,
            pr_url="https://pr/42",
            base_sha="canonical123",
            head_sha="head123",
            is_draft=True,
        ),
        None,
    )
    mock_github.get_ci_status.return_value = (True, CIStatusResult(overall_status="PASS", head_sha="head123", runs=(), details={}), None)

    dispatcher = AutonomousDispatcher(
        config=DispatcherConfig(),
        linear_client=MagicMock(),
        lease_manager=mock_leases,
        worktree_service=MagicMock(),
        github_service=mock_github,
        worktree_base_dir=tmp_path / "worktrees",
        canonical_main_sha="canonical123",
        task_executor=mock_executor,
        execution_ledger=ledger,
    )
    dispatcher._resolve_remote_main_sha = MagicMock(return_value="canonical123")
    dispatcher._validator = mock_validator

    task = LinearTask(
        id="HER-100",
        uuid="uuid-1",
        title="Test Task",
        description="",
        state="Todo",
        priority=1,
        assignee="agent",
        labels=("agent:auto", "agent:shadow"),
        created_at="2026-10-05T00:00:00Z",
        updated_at="2026-10-05T00:00:00Z",
        url="https://linear.app",
    )

    states_written = []
    original_write = ledger.write_state
    def tracking_write(st):
        states_written.append(st.state)
        original_write(st)
    ledger.write_state = tracking_write

    wt_path = tmp_path / "wt"
    wt_path.mkdir(parents=True, exist_ok=True)
    dispatcher._worktree_service.create_worktree.return_value = (wt_path, "feature-branch", None)
    dispatcher._get_git_changes = MagicMock(return_value=("feat.py",))

    with patch.object(AutonomousDispatcher, "_safe_git_run") as mock_safe_git, \
         patch.object(LocalValidator, "run_validation", return_value=(True, {})):
        def fake_git(args, **kw):
            if "rev-parse" in args:
                return MagicMock(returncode=0, stdout="head123\n")
            if "remote" in args:
                return MagicMock(returncode=0, stdout="git@github.com:life2boat/hermes.git\n")
            return MagicMock(returncode=0, stdout="")
        mock_safe_git.side_effect = fake_git

        res = dispatcher.dispatch_one_task([task])

    assert TaskState.COMMITTED.value in states_written
    assert TaskState.BRANCH_PUSHED.value in states_written


def test_recovery_fencing_precedes_cleanup_and_effects(tmp_path: Path):
    """H06: Stale foreign lease halts recovery before any worktree removal."""
    mock_leases = MagicMock()
    mock_leases.verify_lease.return_value = False
    mock_leases.claim.return_value = (False, None, BlockReasonCode.ACTIVE_FOREIGN_LEASE)

    mock_worktree = MagicMock()

    dispatcher = AutonomousDispatcher(
        config=DispatcherConfig(),
        linear_client=MagicMock(),
        lease_manager=mock_leases,
        worktree_service=mock_worktree,
        github_service=MagicMock(),
        worktree_base_dir=tmp_path / "worktrees",
        canonical_main_sha="canonical123",
    )

    recovery_state = ExecutionState(
        task_id="HER-100",
        state=TaskState.WRITEBACK_DONE.value,
        claim_owner="foreign-worker",
        claim_token="token-1",
        worktree_path=str(tmp_path / "foreign_wt"),
        branch="agent/her-100",
        pr_number=1,
        pr_url="https://github.com/life2boat/hermes/pull/1",
        head_sha="head123",
        base_sha="base123",
    )

    res = dispatcher.recover_task(recovery_state)
    assert res.final_state == TaskState.BLOCKED
    assert res.block_reason == BlockReasonCode.ACTIVE_FOREIGN_LEASE.value
    assert not mock_worktree.remove_worktree.called


# ============================================================================
# H10 Additions: Header-Only Database Rejected
# ============================================================================

def test_restore_rejects_header_only_corrupt_database(tmp_path: Path):
    """H10: Ensure restore_quick_snapshot rejects 16-byte SQLite format 3 dummy header."""
    home = tmp_path / "hermes_home"
    home.mkdir()
    valid_db = home / "state.db"
    with sqlite3.connect(valid_db) as conn:
        conn.execute("CREATE TABLE t (id INT);")

    snap_dir = home / "state-snapshots" / "snap-header-only"
    snap_dir.mkdir(parents=True)
    (snap_dir / "state.db").write_bytes(b"SQLite format 3\x00" + b"\x00" * 84)
    manifest = {"files": {"state.db": 100}}
    (snap_dir / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8")

    restored = restore_quick_snapshot("snap-header-only", hermes_home=home)
    assert restored is False


# ============================================================================
# N01 & N02: Secret Scanner CLI & Backup Handle Closure
# ============================================================================

def test_secret_scanner_nonexistent_path_fails_closed(tmp_path: Path):
    """N01: Ensure secret_scanner.main returns exit code 1 when target paths do not exist."""
    from scripts.secret_scanner import main as scanner_main
    missing_file = tmp_path / "nonexistent_target_dir_or_file"
    exit_code = scanner_main([str(missing_file)])
    assert exit_code == 1


def test_safe_copy_db_does_not_leak_connection_handle(tmp_path: Path):
    """N02: Ensure _safe_copy_db explicitly closes verify_conn so destination can be deleted immediately."""
    src = tmp_path / "src.db"
    with sqlite3.connect(src) as conn:
        conn.execute("CREATE TABLE t (id INT);")
        conn.execute("INSERT INTO t VALUES (1);")
    dst = tmp_path / "dst.db"
    ok = _safe_copy_db(src, dst)
    assert ok is True
    # Deleting dst immediately must succeed without WinError 32
    dst.unlink()
    assert not dst.exists()
